name: Deploy React App to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Pull code from GitHub
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js (version matches your local dev)
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Step 3: Install dependencies and build React app
      - name: Install dependencies
        run: npm ci

      - name: Build React app
        run: npm run build

      # Step 4: Configure AWS credentials (from GitHub Secrets)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ACCESSKEY }}
          aws-secret-access-key: ${{ secrets.SECRETACCESSKEY}}
          aws-region: eu-west-1 # change if needed

      # Step 5: Deploy the built app to S3
      - name: Sync build folder to S3
        run: aws s3 sync build/ s3://anirank.ie --delete

